DROP TABLE IF EXISTS books CASCADE;

CREATE TABLE BOOKS (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  publishing_year INTEGER NOT NULL,
  image_url VARCHAR(255),
  isbn VARCHAR(13) NOT NULL

);